package org.mounanga.accounting.common.enums;

public enum LiabilityType {
    ACCOUNTS_PAYABLE,
    SHORT_TERM_LOANS,
    ACCRUED_EXPENSES,
    TAXES_PAYABLE,
    UNEARNED_REVENUE,
    CURRENT_PORTION_OF_LONG_TERM_DEBT,
    LONG_TERM_LOANS,
    BONDS_PAYABLE,
    DEFERRED_TAX_LIABILITIES,
    LEASE_OBLIGATIONS,
    PENSION_LIABILITIES,
    PENDING_LAWSUITS,
    PRODUCT_WARRANTIES,
    ENVIRONMENTAL_CLEANUP_COSTS,
    DERIVATIVE_LIABILITIES,
    FINANCIAL_GUARANTEES
}
